name: SpawnWithItems
main: SpawnWithItems\Main
version: 1.2
api: 3.15.0
load: POSTWORLD
permissions:
  spawnwithitems:
    description: Allows access to all SpawnWithItems features.
    default: false
    children:
      spawnwithitems.receive:
        description: Allows access to receiving items when you spawn.
        default: true
